version: "3.3"
services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    ports: 
      - "8000:80"
    volumes:
      - ./www/:/var/www/
  database:
    image: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  dbdata: